version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: e2ee
      POSTGRES_PASSWORD: e2ee
      POSTGRES_DB: e2ee
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

volumes:
  dbdata:
