/**
 *
 *  Devices.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Devices.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::e2ee;

const std::string Devices::Cols::_id = "\"id\"";
const std::string Devices::Cols::_user_id = "\"user_id\"";
const std::string Devices::Cols::_identity_pubkey = "\"identity_pubkey\"";
const std::string Devices::Cols::_push_token = "\"push_token\"";
const std::string Devices::Cols::_last_seen = "\"last_seen\"";
const std::string Devices::primaryKeyName = "id";
const bool Devices::hasPrimaryKey = true;
const std::string Devices::tableName = "\"devices\"";

const std::vector<typename Devices::MetaData> Devices::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"user_id","int32_t","integer",4,0,0,0},
{"identity_pubkey","std::string","text",0,0,0,1},
{"push_token","std::string","text",0,0,0,0},
{"last_seen","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &Devices::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Devices::Devices(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if(!r["identity_pubkey"].isNull())
        {
            identityPubkey_=std::make_shared<std::string>(r["identity_pubkey"].as<std::string>());
        }
        if(!r["push_token"].isNull())
        {
            pushToken_=std::make_shared<std::string>(r["push_token"].as<std::string>());
        }
        if(!r["last_seen"].isNull())
        {
            auto timeStr = r["last_seen"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastSeen_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            identityPubkey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            pushToken_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastSeen_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Devices::Devices(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            identityPubkey_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            pushToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastSeen_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Devices::Devices(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("identity_pubkey"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["identity_pubkey"].isNull())
        {
            identityPubkey_=std::make_shared<std::string>(pJson["identity_pubkey"].asString());
        }
    }
    if(pJson.isMember("push_token"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["push_token"].isNull())
        {
            pushToken_=std::make_shared<std::string>(pJson["push_token"].asString());
        }
    }
    if(pJson.isMember("last_seen"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["last_seen"].isNull())
        {
            auto timeStr = pJson["last_seen"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastSeen_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Devices::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            identityPubkey_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            pushToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastSeen_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Devices::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("identity_pubkey"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["identity_pubkey"].isNull())
        {
            identityPubkey_=std::make_shared<std::string>(pJson["identity_pubkey"].asString());
        }
    }
    if(pJson.isMember("push_token"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["push_token"].isNull())
        {
            pushToken_=std::make_shared<std::string>(pJson["push_token"].asString());
        }
    }
    if(pJson.isMember("last_seen"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["last_seen"].isNull())
        {
            auto timeStr = pJson["last_seen"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastSeen_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &Devices::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Devices::getId() const noexcept
{
    return id_;
}
void Devices::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Devices::PrimaryKeyType & Devices::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Devices::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Devices::getUserId() const noexcept
{
    return userId_;
}
void Devices::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[1] = true;
}
void Devices::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Devices::getValueOfIdentityPubkey() const noexcept
{
    static const std::string defaultValue = std::string();
    if(identityPubkey_)
        return *identityPubkey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Devices::getIdentityPubkey() const noexcept
{
    return identityPubkey_;
}
void Devices::setIdentityPubkey(const std::string &pIdentityPubkey) noexcept
{
    identityPubkey_ = std::make_shared<std::string>(pIdentityPubkey);
    dirtyFlag_[2] = true;
}
void Devices::setIdentityPubkey(std::string &&pIdentityPubkey) noexcept
{
    identityPubkey_ = std::make_shared<std::string>(std::move(pIdentityPubkey));
    dirtyFlag_[2] = true;
}

const std::string &Devices::getValueOfPushToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(pushToken_)
        return *pushToken_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Devices::getPushToken() const noexcept
{
    return pushToken_;
}
void Devices::setPushToken(const std::string &pPushToken) noexcept
{
    pushToken_ = std::make_shared<std::string>(pPushToken);
    dirtyFlag_[3] = true;
}
void Devices::setPushToken(std::string &&pPushToken) noexcept
{
    pushToken_ = std::make_shared<std::string>(std::move(pPushToken));
    dirtyFlag_[3] = true;
}
void Devices::setPushTokenToNull() noexcept
{
    pushToken_.reset();
    dirtyFlag_[3] = true;
}

const ::trantor::Date &Devices::getValueOfLastSeen() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastSeen_)
        return *lastSeen_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Devices::getLastSeen() const noexcept
{
    return lastSeen_;
}
void Devices::setLastSeen(const ::trantor::Date &pLastSeen) noexcept
{
    lastSeen_ = std::make_shared<::trantor::Date>(pLastSeen);
    dirtyFlag_[4] = true;
}
void Devices::setLastSeenToNull() noexcept
{
    lastSeen_.reset();
    dirtyFlag_[4] = true;
}

void Devices::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Devices::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "identity_pubkey",
        "push_token",
        "last_seen"
    };
    return inCols;
}

void Devices::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdentityPubkey())
        {
            binder << getValueOfIdentityPubkey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPushToken())
        {
            binder << getValueOfPushToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getLastSeen())
        {
            binder << getValueOfLastSeen();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Devices::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void Devices::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIdentityPubkey())
        {
            binder << getValueOfIdentityPubkey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPushToken())
        {
            binder << getValueOfPushToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getLastSeen())
        {
            binder << getValueOfLastSeen();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Devices::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getIdentityPubkey())
    {
        ret["identity_pubkey"]=getValueOfIdentityPubkey();
    }
    else
    {
        ret["identity_pubkey"]=Json::Value();
    }
    if(getPushToken())
    {
        ret["push_token"]=getValueOfPushToken();
    }
    else
    {
        ret["push_token"]=Json::Value();
    }
    if(getLastSeen())
    {
        ret["last_seen"]=getLastSeen()->toDbStringLocal();
    }
    else
    {
        ret["last_seen"]=Json::Value();
    }
    return ret;
}

Json::Value Devices::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIdentityPubkey())
            {
                ret[pMasqueradingVector[2]]=getValueOfIdentityPubkey();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getPushToken())
            {
                ret[pMasqueradingVector[3]]=getValueOfPushToken();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getLastSeen())
            {
                ret[pMasqueradingVector[4]]=getLastSeen()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getIdentityPubkey())
    {
        ret["identity_pubkey"]=getValueOfIdentityPubkey();
    }
    else
    {
        ret["identity_pubkey"]=Json::Value();
    }
    if(getPushToken())
    {
        ret["push_token"]=getValueOfPushToken();
    }
    else
    {
        ret["push_token"]=Json::Value();
    }
    if(getLastSeen())
    {
        ret["last_seen"]=getLastSeen()->toDbStringLocal();
    }
    else
    {
        ret["last_seen"]=Json::Value();
    }
    return ret;
}

bool Devices::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("identity_pubkey"))
    {
        if(!validJsonOfField(2, "identity_pubkey", pJson["identity_pubkey"], err, true))
            return false;
    }
    else
    {
        err="The identity_pubkey column cannot be null";
        return false;
    }
    if(pJson.isMember("push_token"))
    {
        if(!validJsonOfField(3, "push_token", pJson["push_token"], err, true))
            return false;
    }
    if(pJson.isMember("last_seen"))
    {
        if(!validJsonOfField(4, "last_seen", pJson["last_seen"], err, true))
            return false;
    }
    return true;
}
bool Devices::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Devices::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("identity_pubkey"))
    {
        if(!validJsonOfField(2, "identity_pubkey", pJson["identity_pubkey"], err, false))
            return false;
    }
    if(pJson.isMember("push_token"))
    {
        if(!validJsonOfField(3, "push_token", pJson["push_token"], err, false))
            return false;
    }
    if(pJson.isMember("last_seen"))
    {
        if(!validJsonOfField(4, "last_seen", pJson["last_seen"], err, false))
            return false;
    }
    return true;
}
bool Devices::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Devices::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
